//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.23 at 08:57:57 AM IST 
//


package com.jaxb.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jaxb.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StubConfig_QNAME = new QName("", "stubConfig");
    private final static QName _ServiceDefTypeStubDef_QNAME = new QName("", "stubDef");
    private final static QName _StubDefTypeRequestConfig_QNAME = new QName("", "requestConfig");
    private final static QName _StubDefTypeResponseConfig_QNAME = new QName("", "responseConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jaxb.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StubConfigType }
     * 
     */
    public StubConfigType createStubConfigType() {
        return new StubConfigType();
    }

    /**
     * Create an instance of {@link MatchTagType }
     * 
     */
    public MatchTagType createMatchTagType() {
        return new MatchTagType();
    }

    /**
     * Create an instance of {@link MatchersType }
     * 
     */
    public MatchersType createMatchersType() {
        return new MatchersType();
    }

    /**
     * Create an instance of {@link RequestConfigType }
     * 
     */
    public RequestConfigType createRequestConfigType() {
        return new RequestConfigType();
    }

    /**
     * Create an instance of {@link ResponseConfigType }
     * 
     */
    public ResponseConfigType createResponseConfigType() {
        return new ResponseConfigType();
    }

    /**
     * Create an instance of {@link StubDefType }
     * 
     */
    public StubDefType createStubDefType() {
        return new StubDefType();
    }

    /**
     * Create an instance of {@link ServiceDefType }
     * 
     */
    public ServiceDefType createServiceDefType() {
        return new ServiceDefType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StubConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stubConfig")
    public JAXBElement<StubConfigType> createStubConfig(StubConfigType value) {
        return new JAXBElement<StubConfigType>(_StubConfig_QNAME, StubConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StubDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stubDef", scope = ServiceDefType.class)
    public JAXBElement<StubDefType> createServiceDefTypeStubDef(StubDefType value) {
        return new JAXBElement<StubDefType>(_ServiceDefTypeStubDef_QNAME, StubDefType.class, ServiceDefType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "requestConfig", scope = StubDefType.class)
    public JAXBElement<RequestConfigType> createStubDefTypeRequestConfig(RequestConfigType value) {
        return new JAXBElement<RequestConfigType>(_StubDefTypeRequestConfig_QNAME, RequestConfigType.class, StubDefType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "responseConfig", scope = StubDefType.class)
    public JAXBElement<ResponseConfigType> createStubDefTypeResponseConfig(ResponseConfigType value) {
        return new JAXBElement<ResponseConfigType>(_StubDefTypeResponseConfig_QNAME, ResponseConfigType.class, StubDefType.class, value);
    }

}
